services:
  frontend:
    hostname: frontend
    ports:
      - 80:5000
    build:
      context: frontend
      dockerfile: Dockerfile
    read_only: true
    restart: "no"
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    environment:
      KAFKA: kafka:9092
  manager:
    build:
      context: manager
    read_only: true
    restart: "no"
    environment:
      KAFKA: kafka:9092
      RABBITMQ: rabbitmq
  grayscaler:
    build:
      context: grayscaler
    read_only: true
    restart: "no"
    environment:
      RABBITMQ: rabbitmq

  # infra stuff
  kafka:
    build:
      context: kafka
    hostname: kafka
    restart: "no"
    #expose:
    #  - "9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    restart: "no"
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE

version: "3"