services:
  frontend:
    hostname: frontend
    ports:
      - 80:5000
    build:
      context: frontend
      dockerfile: Dockerfile
    read_only: true
    restart: "no"
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    environment:
      KAFKA: kafka:9092
    tmpfs:
      - /tmp
  manager:
    build:
      context: manager
    read_only: true
    restart: "no"
    environment:
      KAFKA: kafka:9092
  grayscaler:
    build:
      context: grayscaler
    read_only: true
    restart: "no"
    environment:
      KAFKA: kafka:9092

  # infra stuff
  kafka:
    build:
      context: kafka
    hostname: kafka
    restart: "always"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    cap_drop:
      - all
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    tmpfs:
    - /tmp/kafka-logs
    - /tmp/zookeeper

version: "3"